services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: laravel_appvehiculo
    ports:
      - "8000:8000" # Este puerto puede ser usado para desarrollo local
    working_dir: /var/www
    volumes:
      - .:/var/www # Este volumen comparte el proyecto con el contenedor
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel_dbvehiculo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: restaurante
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_webservervehiculo
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
